baseURL = "http://blog.lazy.icu"
languageCode = "zh-Hans"
defaultContentLanguage = "zh-hans"
title = "码魂"
theme = "maupassant"
summaryLength = 140 
## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true
hasCJKLanguage = true


[author]
  name = "码魂"

[params]
  author = "码魂"
  subtitle = "专注于Java、移动互联网、移动支付、项目管理、软件架构"
  keywords = "码魂,java,android,博客,项目管理,微信,软件架构,公众号,小程序"
  description = "专注于IT互联网，包括但不限于专注于Java、移动互联网、移动支付、项目管理、软件架构等"
  busuanzi = true
  beian = "计划中..."
  fancybox = true
  localSearch = true
  
[menu]
  [[menu.main]]
    identifier = "tools"
    name = "工具"
    url = "/tools/"
    weight = 2
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4

[[params.links]]
  title = "TailWindCSS文档"
  name = "TailWindCSS文档"
  url = "https://www.tailwindcss.cn/docs"
[[params.links]]
  title = "DaisyUI"
  name = "DaisyUI"
  url = "https://daisyui.com"
[[params.links]]
  title = "shuttle-rs"
  name = "shuttle-rs"
  url = "https://www.shuttle.rs"
[[params.links]]
  title = "icones"
  name = "icones"
  url = "https://icones.js.org"

# [[params.ads]]
#   title = "【渠道专享低折扣】11月特惠 限时2折"
#   url = "https://www.aliyun.com/acts/limit-buy?userCode=jdg9oj97"
#   img = "https://img.alicdn.com/tfs/TB1hblJl7Y2gK0jSZFgXXc5OFXa-750-400.jpg"

## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

[params.utteranc]
    enable = true
    repo = "pkptzx/blog"
    issueTerm = "pathname"
    theme = "github-light"
  
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"
    
    
    
    
  
